FROM node:18 AS builder

WORKDIR /app

COPY package.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

FROM node:18-slim

WORKDIR /app

COPY --from=builder /app/package.json .
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone/ ./
COPY --from=builder /app/.next/static ./.next/static

RUN npm install --production --legacy-peer-deps

EXPOSE 3007

ENV PORT=3007

CMD ["node", "server.js", "--host", "0.0.0.0", "--port", "3037"]
