services:
  nest-zero-web:
    container_name: nest_zero_web
    build:
      context: .
      dockerfile: Dockerfile.${CI_ENVIRONMENT_NAME}
    image: nest-zero-web:${CI_ENVIRONMENT_NAME}
    ports:
      - ${FE_CONTAINER_PORT}:${FE_PORT}
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_URL_API=${NEXT_PUBLIC_URL_API}

networks:
  default:
    name: nest-zero-development
    driver: bridge
