variables:
  BE_VERSION: 0.0.0
  BE_IMAGE_NAME: nest_zero_api
  BE_CONTAINER_NAME: nest_zero_api
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

build_backend_development:
  stage: build
  environment:
    name: development
  before_script:
    - cd $BE_WORKDIR
    - chmod +x ./scripts/prepare-env.sh
    - ./scripts/prepare-env.sh
  script:
    - echo "Build docker image ${CI_ENVIRONMENT_NAME}"
    - docker compose --env-file .env -f docker-compose.yml build nest-zero-api
    - rm -f .env
    - echo "Remove unused image"
    - docker image prune -f --filter "dangling=true"
    - echo "Build completed successfully"
  only:
    - develop
  tags:
    - zero-backend-runner

build_backend_production:
  stage: build
  environment:
    name: production
  before_script:
    - cd $BE_WORKDIR
    - chmod +x ./scripts/prepare-env.sh
    - ./scripts/prepare-env.sh
  script:
    - echo "Build docker image ${CI_ENVIRONMENT_NAME}"
    - docker build --build-arg CACHE_BUST=$BE_VERSION -t "${BE_IMAGE_NAME}_${CI_ENVIRONMENT_NAME}" -f Dockerfile .
    - rm -f .env
    - echo "Assign tag for docker image"
    - docker tag "${BE_IMAGE_NAME}_${CI_ENVIRONMENT_NAME}" $CI_REGISTRY/$BE_IMAGE_NAME:$BE_VERSION-$CI_ENVIRONMENT_NAME
    - echo "Push image to local registry"
    - docker push $CI_REGISTRY/$BE_IMAGE_NAME:$BE_VERSION-$CI_ENVIRONMENT_NAME
    - echo "Remove unused image"
    - docker image prune -f --filter "dangling=true"
    - echo "Build completed successfully"
  only:
    - main
  tags:
    - zero-backend-runner

deploy_backend_development:
  before_script:
    - echo "This is a before script that runs before job."
    - cd $BE_WORKDIR
  environment:
    name: development
  stage: deploy
  script:
    - echo "Stop and remove current container"
    - docker stop "${BE_CONTAINER_NAME}_${CI_ENVIRONMENT_NAME}" || true
    - docker rm "${BE_CONTAINER_NAME}_${CI_ENVIRONMENT_NAME}" || true
    - echo "Run container"
    - docker compose -f docker-compose.yml up -d --remove-orphans
    - echo "Running deploy process..."
    - echo "Deploy ${CI_ENVIRONMENT_NAME} environment completed!"
  only:
    - develop
  tags:
    - zero-backend-runner

deploy_backend_production:
  environment:
    name: production
  stage: deploy
  script:
    - echo "Stop and remove current container"
    - docker container stop "${BE_CONTAINER_NAME}_${CI_ENVIRONMENT_NAME}" || true
    - docker container rm "${BE_CONTAINER_NAME}_${CI_ENVIRONMENT_NAME}" || true
    - echo "Remove unused image"
    - docker image prune -f --filter "dangling=true"
    - echo "Running deploy process..."
    - echo "Pull image from local registry"
    - docker pull $CI_REGISTRY/$BE_IMAGE_NAME:$BE_VERSION-$CI_ENVIRONMENT_NAME
    - echo "Run container"
    - |
      docker run -d \
        --name "${BE_CONTAINER_NAME}_${CI_ENVIRONMENT_NAME}" \
        -p $BE_PORT:$BE_PORT \
        --network nest-zero-production \
        -v "nest-zero-be-app:/usr/src/app" \
        -v "nest-zero-be-app-data:/usr/src/app/node_modules" \
        "$CI_REGISTRY/$BE_IMAGE_NAME:$BE_VERSION-$CI_ENVIRONMENT_NAME"
    - echo "Deploy ${CI_ENVIRONMENT_NAME} environment completed!"
  only:
    - main
  tags:
    - zero-backend-runner

