services:
  nest-zero-mysql:
    image: mysql:8.0
    container_name: nest-zero-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - ${DATABASE_PORT}:${MYSQL_TCP_PORT}
    volumes:
      - nest-zero-mysql:/var/lib/mysql

  nest-zero-api:
    container_name: nest_zero_api
    image: nest-zero-api-development
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - ${BE_CONTAINER_PORT}:${BE_PORT}
    restart: unless-stopped
    depends_on:
      - nest-zero-mysql

networks:
  default:
    name: nest-zero-development
    driver: bridge
volumes:
  nest-zero-mysql:
    driver: local

