version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: nest_zero_mysql
    restart: always
    networks:
      - default
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

    ports:
      - '3306:3306'
    volumes:
      - mysql:/data/mysql
    env_file:
      - .env

networks:
  default:
    name: nest-zero-development
    driver: bridge
volumes:
  mysql:
    driver: local
